#define OPCODE_TABLE(X)                            \
	X(7, brk,         implied,   0x00)                  \
	X(6, ora,         indx,      0x01)                  \
	X(2, nop,         implied,   0x02)                  \
	X(2, nop,         implied,   0x03)                  \
	X(3, tsbzp,       zp,        0x04)                  \
	X(3, orazp,       zp,        0x05)                  \
	X(5, aslzp,       zp,        0x06)                  \
	X(2, nop,         implied,   0x07)                  \
	X(3, php,         implied,   0x08)                  \
	X(3, ora,         immediate, 0x09)                  \
	X(2, asla,        implied,   0x0A)                  \
	X(2, ora,         implied,   0x0B)                  \
	X(4, tsb,         abs,       0x0C)                  \
	X(4, ora,         abs,       0x0D)                  \
	X(6, asl,         abs,       0x0E)                  \
	X(2, nop,         implied,   0x0F)                  \
	X(2, bpl,         relative,  0x10)                  \
	X(5, ora,         indy,      0x11)                  \
	X(3, oraindzp,    indzp,     0x12)                  \
	X(2, nop,         implied,   0x13)                  \
	X(3, trbzp,       zp,        0x14)                  \
	X(4, orazpx,      zpx,       0x15)                  \
	X(6, aslzpx,      zpx,       0x16)                  \
	X(2, nop,         implied,   0x17)                  \
	X(2, clc,         implied,   0x18)                  \
	X(4, ora,         absy,      0x19)                  \
	X(2, ina,         implied,   0x1A)                  \
	X(2, nop,         implied,   0x1B)                  \
	X(4, trb,         abs,       0x1C)                  \
	X(4, ora,         absx,      0x1D)                  \
	X(7, asl,         absx,      0x1E)                  \
	X(2, nop,         implied,   0x1F)                  \
	X(6, jsr,         abs,       0x20)                  \
	X(6, and,         indx,      0x21)                  \
	X(2, nop,         implied,   0x22)                  \
	X(2, nop,         implied,   0x23)                  \
	X(3, bitzp,       zp,        0x24)                  \
	X(3, andzp,       zp,        0x25)                  \
	X(5, rolzp,       zp,        0x26)                  \
	X(2, nop,         implied,   0x27)                  \
	X(4, plp,         implied,   0x28)                  \
	X(3, and,         immediate, 0x29)                  \
	X(2, rola,        implied,   0x2A)                  \
	X(2, nop,         implied,   0x2B)                  \
	X(4, bit,         abs,       0x2C)                  \
	X(4, and,         abs,       0x2D)                  \
	X(6, rol,         abs,       0x2E)                  \
	X(2, nop,         implied,   0x2F)                  \
	X(2, bmi,         relative,  0x30)                  \
	X(5, and,         indy,      0x31)                  \
	X(3, andindzp,    indzp,     0x32)                  \
	X(2, nop,         implied,   0x33)                  \
	X(4, bitzpx,      zpx,       0x34)                  \
	X(4, andzpx,      zpx,       0x35)                  \
	X(6, rolzpx,      zpx,       0x36)                  \
	X(2, nop,         implied,   0x37)                  \
	X(2, sec,         implied,   0x38)                  \
	X(4, and,         absy,      0x39)                  \
	X(2, dea,         implied,   0x3A)                  \
	X(2, nop,         implied,   0x3B)                  \
	X(4, bit,         absx,      0x3C)                  \
	X(4, and,         absx,      0x3D)                  \
	X(7, rol,         absx,      0x3E)                  \
	X(2, nop,         implied,   0x3F)                  \
	X(6, rti,         implied,   0x40)                  \
	X(6, eor,         indx,      0x41)                  \
	X(2, nop,         implied,   0x42)                  \
	X(2, nop,         implied,   0x43)                  \
	X(2, nop,         implied,   0x44)                  \
	X(3, eorzp,       zp,        0x45)                  \
	X(5, lsrzp,       zp,        0x46)                  \
	X(2, nop,         implied,   0x47)                  \
	X(3, pha,         implied,   0x48)                  \
	X(3, eor,         immediate, 0x49)                  \
	X(2, lsra,        implied,   0x4A)                  \
	X(2, nop,         implied,   0x4B)                  \
	X(3, jmp,         abs,       0x4C)                  \
	X(4, eor,         abs,       0x4D)                  \
	X(6, lsr,         abs,       0x4E)                  \
	X(2, nop,         implied,   0x4F)                  \
	X(2, bvc,         relative,  0x50)                  \
	X(5, eor,         indy,      0x51)                  \
	X(3, eorindzp,    indzp,     0x52)                  \
	X(2, nop,         implied,   0x53)                  \
	X(2, nop,         implied,   0x54)                  \
	X(4, eorzpx,      zpx,       0x55)                  \
	X(6, lsrzpx,      zpx,       0x56)                  \
	X(2, nop,         implied,   0x57)                  \
	X(2, cli,         implied,   0x58)                  \
	X(4, eor,         absy,      0x59)                  \
	X(3, phy,         implied,   0x5A)                  \
	X(2, nop,         implied,   0x5B)                  \
	X(2, nop,         implied,   0x5C)                  \
	X(4, eor,         absx,      0x5D)                  \
	X(7, lsr,         absx,      0x5E)                  \
	X(2, nop,         implied,   0x5F)                  \
	X(6, rts,         implied,   0x60)                  \
	X(6, adc,         indx,      0x61)                  \
	X(2, nop,         implied,   0x62)                  \
	X(2, nop,         implied,   0x63)                  \
	X(3, stzzp,       zp,        0x64)                  \
	X(3, adczp,       zp,        0x65)                  \
	X(5, rorzp,       zp,        0x66)                  \
	X(2, nop,         implied,   0x67)                  \
	X(4, pla,         implied,   0x68)                  \
	X(3, adc,         immediate, 0x69)                  \
	X(2, rora,        implied,   0x6A)                  \
	X(2, nop,         implied,   0x6B)                  \
	X(5, jmp,         indirect,  0x6C)                  \
	X(4, adc,         abs,       0x6D)                  \
	X(6, ror,         abs,       0x6E)                  \
	X(2, nop,         implied,   0x6F)                  \
	X(2, bvs,         implied,   0x70)                  \
	X(5, adc,         indy,      0x71)                  \
	X(3, adcindzp,    indzp,     0x72)                  \
	X(2, nop,         implied,   0x73)                  \
	X(4, stzzpx,      zpx,       0x74)                  \
	X(4, adczpx,      zpx,       0x75)                  \
	X(6, rorzpx,      zpx,       0x76)                  \
	X(2, nop,         implied,   0x77)                  \
	X(2, sei,         implied,   0x78)                  \
	X(4, adc,         absy,      0x79)                  \
	X(4, ply,         implied,   0x7A)                  \
	X(2, nop,         implied,   0x7B)                  \
	X(6, jmp,         indabsx,   0x7C)                  \
	X(4, adc,         absx,      0x7D)                  \
	X(7, ror,         absx,      0x7E)                  \
	X(2, nop,         implied,   0x7F)                  \
	X(2, bra,         relative,  0x80)                  \
	X(6, sta,         indx,      0x81)                  \
	X(2, nop,         implied,   0x82)                  \
	X(2, nop,         implied,   0x83)                  \
	X(2, styzp,       zp,        0x84)                  \
	X(2, stazp,       zp,        0x85)                  \
	X(2, stxzp,       zp,        0x86)                  \
	X(2, nop,         implied,   0x87)                  \
	X(2, dey,         implied,   0x88)                  \
	X(2, bit,         immediate, 0x89)                  \
	X(2, txa,         implied,   0x8A)                  \
	X(2, nop,         implied,   0x8B)                  \
	X(4, sty,         abs,       0x8C)                  \
	X(4, sta,         abs,       0x8D)                  \
	X(4, stx,         abs,       0x8E)                  \
	X(2, nop,         implied,   0x8F)                  \
	X(2, bcc,         relative,  0x90)                  \
	X(6, sta,         indy,      0x91)                  \
	X(3, staindzp,    indzp,     0x92)                  \
	X(2, nop,         implied,   0x93)                  \
	X(4, styzpx,      zpx,       0x94)                  \
	X(4, stazpx,      zpx,       0x95)                  \
	X(4, stxzpy,      zpy,       0x96)                  \
	X(2, nop,         implied,   0x97)                  \
	X(2, tya,         implied,   0x98)                  \
	X(5, sta,         absy,      0x99)                  \
	X(2, txs,         implied,   0x9A)                  \
	X(2, nop,         implied,   0x9B)                  \
	X(4, stz,         abs,       0x9C)                  \
	X(5, sta,         absx,      0x9D)                  \
	X(5, stz,         absx,      0x9E)                  \
	X(2, nop,         implied,   0x9F)                  \
	X(3, ldy,         immediate, 0xA0)                  \
	X(6, lda,         indx,      0xA1)                  \
	X(3, ldx,         immediate, 0xA2)                  \
	X(2, nop,         implied,   0xA3)                  \
	X(3, ldyzp,       zp,        0xA4)                  \
	X(3, ldazp,       zp,        0xA5)                  \
	X(3, ldxzp,       zp,        0xA6)                  \
	X(2, nop,         implied,   0xA7)                  \
	X(2, tay,         implied,   0xA8)                  \
	X(3, lda,         immediate, 0xA9)                  \
	X(2, tax,         implied,   0xAA)                  \
	X(2, nop,         implied,   0xAB)                  \
	X(4, ldy,         abs,       0xAC)                  \
	X(4, lda,         abs,       0xAD)                  \
	X(4, ldx,         abs,       0xAE)                  \
	X(2, nop,         implied,   0xAF)                  \
	X(2, bcs,         relative,  0xB0)                  \
	X(5, lda,         indy,      0xB1)                  \
	X(3, ldaindzp,    indzp,     0xB2)                  \
	X(2, nop,         implied,   0xB3)                  \
	X(4, ldyzpx,      zpx,       0xB4)                  \
	X(4, ldazpx,      zpx,       0xB5)                  \
	X(4, ldxzpy,      zpy,       0xB6)                  \
	X(2, nop,         implied,   0xB7)                  \
	X(2, clv,         implied,   0xB8)                  \
	X(4, lda,         absy,      0xB9)                  \
	X(2, tsx,         implied,   0xBA)                  \
	X(2, nop,         implied,   0xBB)                  \
	X(4, ldy,         absx,      0xBC)                  \
	X(4, lda,         absx,      0xBD)                  \
	X(4, ldx,         absy,      0xBE)                  \
	X(2, nop,         implied,   0xBF)                  \
	X(3, cpy,         immediate, 0xC0)                  \
	X(6, cmp,         indx,      0xC1)                  \
	X(2, nop,         implied,   0xC2)                  \
	X(2, nop,         implied,   0xC3)                  \
	X(3, cpyzp,       zp,        0xC4)                  \
	X(3, cmpzp,       zp,        0xC5)                  \
	X(5, deczp,       zp,        0xC6)                  \
	X(2, nop,         implied,   0xC7)                  \
	X(2, iny,         implied,   0xC8)                  \
	X(3, cmp,         immediate, 0xC9)                  \
	X(2, dex,         implied,   0xCA)                  \
	X(2, nop,         implied,   0xCB)                  \
	X(4, cpy,         abs,       0xCC)                  \
	X(4, cmp,         abs,       0xCD)                  \
	X(6, dec,         abs,       0xCE)                  \
	X(2, nop,         implied,   0xCF)                  \
	X(2, bne,         relative,  0xD0)                  \
	X(5, cmp,         indy,      0xD1)                  \
	X(3, cmpindzp,    indzp,     0xD2)                  \
	X(2, nop,         implied,   0xD3)                  \
	X(2, nop,         implied,   0xD4)                  \
	X(4, cmpzpx,      zpx,       0xD5)                  \
	X(6, deczpx,      zpx,       0xD6)                  \
	X(2, nop,         implied,   0xD7)                  \
	X(2, cld,         implied,   0xD8)                  \
	X(4, cmp,         absy,      0xD9)                  \
	X(3, phx,         implied,   0xDA)                  \
	X(2, nop,         implied,   0xDB)                  \
	X(2, nop,         implied,   0xDC)                  \
	X(4, cmp,         absx,      0xDD)                  \
	X(7, dec,         absx,      0xDE)                  \
	X(2, nop,         implied,   0xDF)                  \
	X(3, cpx,         immediate, 0xE0)                  \
	X(6, sbc,         indx,      0xE1)                  \
	X(2, nop,         implied,   0xE2)                  \
	X(2, nop,         implied,   0xE3)                  \
	X(3, cpxzp,       zp,        0xE4)                  \
	X(3, sbczp,       zp,        0xE5)                  \
	X(5, inczp,       zp,        0xE6)                  \
	X(2, nop,         implied,   0xE7)                  \
	X(2, inx,         implied,   0xE8)                  \
	X(3, sbc,         immediate, 0xE9)                  \
	X(2, nop,         implied,   0xEA)                  \
	X(2, nop,         implied,   0xEB)                  \
	X(4, cpx,         abs,       0xEC)                  \
	X(4, sbc,         abs,       0xED)                  \
	X(6, inc,         abs,       0xEE)                  \
	X(2, nop,         implied,   0xEF)                  \
	X(2, beq,         relative,  0xF0)                  \
	X(5, sbc,         indy,      0xF1)                  \
	X(3, sbcindzp,    indzp,     0xF2)                  \
	X(2, nop,         implied,   0xF3)                  \
	X(2, nop,         implied,   0xF4)                  \
	X(4, sbczpx,      zpx,       0xF5)                  \
	X(6, inczpx,      zpx,       0xF6)                  \
	X(2, nop,         implied,   0xF7)                  \
	X(2, sed,         implied,   0xF8)                  \
	X(4, sbc,         absy,      0xF9)                  \
	X(4, plx,         implied,   0xFA)                  \
	X(2, nop,         implied,   0xFB)                  \
	X(2, nop,         implied,   0xFC)                  \
	X(4, sbc,         absx,      0xFD)                  \
	X(7, inc,         absx,      0xFE)                  \
	X(2, nop,         implied,   0xFF)   

// #define OPCODE_ENUM_NAME(A, B, C, D) CPU_OP_ ## B ## _ ## C ## _ ## D
// #define OPCODE_ENUM(A, B, C, D) OPCODE_ENUM_NAME(A, B, C, D),
// enum {
// 	OPCODE_TABLE(OPCODE_ENUM)
// };

typedef struct{   
	unsigned short int  ticks;   
	void (*instruction)(void);   
	void (*adrmode)(void);   
} OPCODE;
#define OPCODE_ARR(A, B, C, D) {A, cpu_ ## B, cpu_ ## C}, 
#define OPCODE_TCK(A, B, C, D) A, 
#define OPCODE_STR(A, B, C, D) #B,
// const OPCODE opcodetable[] = {OPCODE_TABLE(OPCODE_ARR)};
const int opcodeticks[] = {OPCODE_TABLE(OPCODE_TCK)};
const char* opcode_names[] = {OPCODE_TABLE(OPCODE_STR)};

#define OPCODE_SWITCH(A, B, C, D) case D: cpu_ ## B(cpu_ ## C); cpu_clockticks += A; break;
static void cpu_execinstruction(uint8_t op) {
	switch (op) {
		OPCODE_TABLE(OPCODE_SWITCH)
	}
}
